def adicionar_gostos(pessoas: list, gostos: list) -> list:

  gostos_dict = {gosto["id"]: gosto["gostos"] for gosto in gostos}
  pessoas_com_gostos = []
  for pessoa in pessoas[:5]:
    pessoa_atualizada = pessoa.copy()
    pessoa_atualizada["gostos"] = gostos_dict.get(pessoa["id"], [])
    pessoas_com_gostos.append(pessoa_atualizada)
  return pessoas_com_gostos



pessoas = [
{"id": 1, "nome": "André", "idade": 39},
{"id": 2, "nome": "Carlos", "idade": 45},
{"id": 3, "nome": "Felipe", "idade": 34},
{"id": 4, "nome": "Lucas", "idade": 34},
{"id": 5, "nome": "Marcos", "idade": 23},
{"id": 6, "nome": "Fernanda", "idade": 31},
{"id": 7, "nome": "Julia", "idade": 20},
{"id": 8, "nome": "Larissa", "idade": 31},
{"id": 9, "nome": "Gustavo", "idade": 41},
{"id": 10, "nome": "Julia", "idade": 46},
{"id": 11, "nome": "Rodrigo", "idade": 50},
{"id": 12, "nome": "Felipe", "idade": 26},
{"id": 13, "nome": "Isabela", "idade": 43},
{"id": 14, "nome": "Ana", "idade": 30},
{"id": 15, "nome": "André", "idade": 26},
{"id": 16, "nome": "Isabela", "idade": 38},
{"id": 17, "nome": "Larissa", "idade": 59},
{"id": 18, "nome": "Beatriz", "idade": 60},
{"id": 19, "nome": "Larissa", "idade": 25},
{"id": 20, "nome": "João", "idade": 36},
{"id": 21, "nome": "Laura", "idade": 57},
{"id": 22, "nome": "Gustavo", "idade": 57},
{"id": 23, "nome": "Lucas", "idade": 40},
{"id": 24, "nome": "Pedro", "idade": 23},
{"id": 25, "nome": "Marcos", "idade": 26},
{"id": 26, "nome": "Larissa", "idade": 18},
{"id": 27, "nome": "Patrícia", "idade": 29},
{"id": 28, "nome": "Isabela", "idade": 39},
{"id": 29, "nome": "Larissa", "idade": 30},
{"id": 30, "nome": "Mariana", "idade": 41},
{"id": 31, "nome": "Rodrigo", "idade": 36},
{"id": 32, "nome": "João", "idade": 18},
{"id": 33, "nome": "Beatriz", "idade": 42},
{"id": 34, "nome": "Patrícia", "idade": 20},
{"id": 35, "nome": "Beatriz", "idade": 21},
{"id": 36, "nome": "Mariana", "idade": 51},
{"id": 37, "nome": "Patrícia", "idade": 45},
{"id": 38, "nome": "Patrícia", "idade": 27},
{"id": 39, "nome": "Isabela", "idade": 31},
{"id": 40, "nome": "Marcos", "idade": 38},
{"id": 41, "nome": "Mariana", "idade": 21},
{"id": 42, "nome": "Rodrigo", "idade": 18},
{"id": 43, "nome": "Isabela", "idade": 44},
{"id": 44, "nome": "Felipe", "idade": 49},
{"id": 45, "nome": "André", "idade": 44},
{"id": 46, "nome": "Rodrigo", "idade": 45},
{"id": 47, "nome": "Camila", "idade": 34},
{"id": 48, "nome": "Carlos", "idade": 45},
{"id": 49, "nome": "Laura", "idade": 40},
{"id": 50, "nome": "Beatriz", "idade": 44},
{"id": 51, "nome": "Felipe", "idade": 53},
{"id": 52, "nome": "Larissa", "idade": 56},
{"id": 53, "nome": "Gustavo", "idade": 49},
{"id": 54, "nome": "João", "idade": 22},
{"id": 55, "nome": "Larissa", "idade": 47},
{"id": 56, "nome": "João", "idade": 51},
{"id": 57, "nome": "Mariana", "idade": 50},
{"id": 58, "nome": "Camila", "idade": 40},
{"id": 59, "nome": "André", "idade": 52},
{"id": 60, "nome": "João", "idade": 58},
{"id": 61, "nome": "Gustavo", "idade": 56},
{"id": 62, "nome": "Felipe", "idade": 25},
{"id": 63, "nome": "Isabela", "idade": 40},
{"id": 64, "nome": "João", "idade": 53},
{"id": 65, "nome": "Marcos", "idade": 25},
{"id": 66, "nome": "Marcos", "idade": 18},
{"id": 67, "nome": "Laura", "idade": 50},
{"id": 68, "nome": "Lucas", "idade": 33},
{"id": 69, "nome": "Laura", "idade": 57},
{"id": 70, "nome": "Marcos", "idade": 42},
{"id": 71, "nome": "Mariana", "idade": 18},
{"id": 72, "nome": "Mariana", "idade": 25},
{"id": 73, "nome": "Rodrigo", "idade": 55},
{"id": 74, "nome": "Laura", "idade": 23},
{"id": 75, "nome": "Felipe", "idade": 43},
{"id": 76, "nome": "Gustavo", "idade": 31},
{"id": 77, "nome": "Patrícia", "idade": 54},
{"id": 78, "nome": "Larissa", "idade": 30},
{"id": 79, "nome": "Felipe", "idade": 24},
{"id": 80, "nome": "Larissa", "idade": 57},
{"id": 81, "nome": "Mariana", "idade": 26},
{"id": 82, "nome": "Felipe", "idade": 23},
{"id": 83, "nome": "Ana", "idade": 56},
{"id": 84, "nome": "Patrícia", "idade": 47},
{"id": 85, "nome": "Mariana", "idade": 26},
{"id": 86, "nome": "Ana", "idade": 57},
{"id": 87, "nome": "Camila", "idade": 20},
{"id": 88, "nome": "André", "idade": 20},
{"id": 89, "nome": "Rafael", "idade": 31},
{"id": 90, "nome": "André", "idade": 53},
{"id": 91, "nome": "Larissa", "idade": 48},
{"id": 92, "nome": "Beatriz", "idade": 44},
{"id": 93, "nome": "Gustavo", "idade": 31},
{"id": 94, "nome": "Felipe", "idade": 58},
{"id": 95, "nome": "Laura", "idade": 55},
{"id": 96, "nome": "Lucas", "idade": 28},
{"id": 97, "nome": "Larissa", "idade": 23},
{"id": 98, "nome": "Fernanda", "idade": 30},
{"id": 99, "nome": "Mariana", "idade": 32},
{"id": 100, "nome": "Pedro", "idade": 39}
]

gostos = [
{"id": 1, "gostos": ['Moda', 'Ciência']},
{"id": 2, "gostos": ['História', 'Games', 'Viagem']},
{"id": 3, "gostos": ['Cinema', 'Natureza']},
{"id": 4, "gostos": ['Natureza', 'Futebol']},
{"id": 5, "gostos": ['Política', 'Dança', 'Viagem', 'Natureza']},
{"id": 6, "gostos": ['Leitura', 'Ciência', 'História', 'Política', 'Natureza']},
{"id": 7, "gostos": ['Carros']},
{"id": 8, "gostos": ['História', 'Games']},
{"id": 9, "gostos": ['Carros', 'Fotografia', 'Arte']},
{"id": 10, "gostos": ['Fotografia', 'Leitura', 'Culinária']},
{"id": 11, "gostos": ['Viagem', 'Teatro', 'História', 'Games']},
{"id": 12, "gostos": ['Moda', 'Cinema', 'Fotografia']},
{"id": 13, "gostos": ['Ciência', 'Arte']},
{"id": 14, "gostos": ['Tecnologia']},
{"id": 15, "gostos": ['Teatro', 'Música', 'Dança', 'Tecnologia', 'História']},
{"id": 16, "gostos": ['Games', 'Viagem', 'Pets']},
{"id": 17, "gostos": ['Política', 'Dança', 'Futebol', 'Cinema', 'Arte']},
{"id": 18, "gostos": ['Pets', 'Leitura', 'Carros', 'Viagem', 'Tecnologia']},
{"id": 19, "gostos": ['História']},
{"id": 20, "gostos": ['Culinária', 'Tecnologia', 'Natureza', 'Moda']},
{"id": 21, "gostos": ['Arte']},
{"id": 22, "gostos": ['Ciência', 'Teatro', 'Cinema', 'Fotografia', 'História']},
{"id": 23, "gostos": ['Games']},
{"id": 24, "gostos": ['Tecnologia']},
{"id": 25, "gostos": ['Natureza', 'Dança', 'Cinema']},
{"id": 26, "gostos": ['Pets', 'Política', 'Natureza', 'Leitura']},
{"id": 27, "gostos": ['Tecnologia', 'Dança', 'Futebol', 'Arte']},
{"id": 28, "gostos": ['Música', 'Esportes', 'Dança', 'Carros', 'Tecnologia']},
{"id": 29, "gostos": ['Arte', 'Fotografia', 'Carros']},
{"id": 30, "gostos": ['Pets', 'Tecnologia', 'Natureza', 'Dança']},
{"id": 31, "gostos": ['Cinema', 'Tecnologia']},
{"id": 32, "gostos": ['Carros', 'Música', 'Ciência', 'História', 'Arte']},
{"id": 33, "gostos": ['Teatro', 'Leitura']},
{"id": 34, "gostos": ['Pets', 'Carros', 'Viagem', 'Dança']},
{"id": 35, "gostos": ['Política', 'Futebol', 'Teatro', 'Viagem', 'Ciência']},
{"id": 36, "gostos": ['História', 'Pets', 'Natureza']},
{"id": 37, "gostos": ['Games', 'Culinária']},
{"id": 38, "gostos": ['Música']},
{"id": 39, "gostos": ['Moda', 'Culinária', 'História']},
{"id": 40, "gostos": ['Esportes']},
{"id": 41, "gostos": ['Carros', 'Teatro', 'Pets']},
{"id": 42, "gostos": ['Leitura']},
{"id": 43, "gostos": ['Carros', 'Esportes', 'Culinária', 'Música']},
{"id": 44, "gostos": ['Futebol']},
{"id": 45, "gostos": ['Natureza', 'Carros']},
{"id": 46, "gostos": ['Culinária']},
{"id": 47, "gostos": ['Culinária', 'Leitura', 'Natureza', 'Fotografia']},
{"id": 48, "gostos": ['Ciência', 'Viagem', 'Política', 'Música']},
{"id": 49, "gostos": ['Fotografia', 'Viagem']},
{"id": 50, "gostos": ['Moda', 'Teatro', 'Esportes', 'Culinária']},
{"id": 51, "gostos": ['Política']},
{"id": 52, "gostos": ['Arte', 'Natureza', 'Teatro', 'Moda']},
{"id": 53, "gostos": ['Games']},
{"id": 54, "gostos": ['Arte', 'Games', 'Música']},
{"id": 55, "gostos": ['Leitura']},
{"id": 56, "gostos": ['Esportes', 'Tecnologia', 'Games', 'Música', 'Futebol']},
{"id": 57, "gostos": ['Fotografia', 'Tecnologia', 'Natureza']},
{"id": 58, "gostos": ['Esportes', 'Teatro']},
{"id": 59, "gostos": ['Tecnologia', 'Arte', 'Cinema']},
{"id": 60, "gostos": ['Teatro', 'História', 'Moda', 'Tecnologia']},
{"id": 61, "gostos": ['Arte', 'Teatro', 'História']},
{"id": 62, "gostos": ['Dança', 'Ciência', 'História', 'Pets']},
{"id": 63, "gostos": ['Política', 'Leitura', 'Futebol']},
{"id": 64, "gostos": ['Viagem', 'Teatro', 'Música']},
{"id": 65, "gostos": ['Arte', 'Ciência', 'Leitura', 'Natureza']},
{"id": 66, "gostos": ['Cinema', 'Fotografia', 'Moda', 'Natureza']},
{"id": 67, "gostos": ['Natureza', 'Arte', 'Viagem', 'Culinária']},
{"id": 68, "gostos": ['Leitura', 'Games', 'Carros']},
{"id": 69, "gostos": ['Música', 'História', 'Natureza']},
{"id": 70, "gostos": ['Dança', 'Futebol', 'História']},
{"id": 71, "gostos": ['Música']},
{"id": 72, "gostos": ['Carros', 'Esportes', 'História', 'Arte', 'Música']},
{"id": 73, "gostos": ['Dança', 'Culinária']},
{"id": 74, "gostos": ['Moda', 'Fotografia', 'Tecnologia']},
{"id": 75, "gostos": ['Teatro', 'Leitura', 'Arte', 'Política']},
{"id": 76, "gostos": ['Política', 'Games', 'Culinária', 'Fotografia']},
{"id": 77, "gostos": ['Games', 'Viagem', 'Culinária']},
{"id": 78, "gostos": ['Ciência', 'Dança']},
{"id": 79, "gostos": ['História', 'Música', 'Cinema', 'Natureza', 'Moda']},
{"id": 80, "gostos": ['Ciência', 'Esportes', 'Leitura', 'Carros']},
{"id": 81, "gostos": ['Natureza']},
{"id": 82, "gostos": ['Natureza', 'Games', 'Teatro']},
{"id": 83, "gostos": ['Ciência', 'Arte']},
{"id": 84, "gostos": ['Música', 'Natureza', 'Culinária', 'Arte', 'História']},
{"id": 85, "gostos": ['Culinária']},
{"id": 86, "gostos": ['Música', 'Futebol']},
{"id": 87, "gostos": ['Pets', 'Viagem', 'Tecnologia', 'Teatro', 'Fotografia']},
{"id": 88, "gostos": ['Culinária', 'Dança', 'Moda']},
{"id": 89, "gostos": ['Moda', 'Política', 'Teatro', 'Dança', 'Fotografia']},
{"id": 90, "gostos": ['Arte']},
{"id": 91, "gostos": ['Fotografia', 'Culinária', 'Dança']},
{"id": 92, "gostos": ['História']},
{"id": 93, "gostos": ['História', 'Esportes', 'Dança', 'Futebol']},
{"id": 94, "gostos": ['Cinema', 'Fotografia', 'Futebol', 'Culinária']},
{"id": 95, "gostos": ['Cinema']},
{"id": 96, "gostos": ['Futebol']},
{"id": 97, "gostos": ['Culinária', 'História', 'Política']},
{"id": 98, "gostos": ['Futebol', 'Tecnologia']},
{"id": 99, "gostos": ['História', 'Culinária', 'Teatro', 'Viagem', 'Política']},
{"id": 100, "gostos": ['Pets', 'Viagem', 'Cinema', 'Fotografia', 'Esportes']}
]

resultado = adicionar_gostos(pessoas, gostos)
import pandas as pd

def exportar_csv(pessoas: list, nome_arquivo: str):

  df = pd.DataFrame(pessoas)
  df.to_csv(nome_arquivo, index=False)
  print(f"Dados exportados para '{nome_arquivo}' com sucesso.")



exportar_csv(resultado, "pessoas.csv")